# Generated by Django 3.0.5 on 2020-04-27 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
